# Generated by Django 4.2.5 on 2023-10-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lendrequest',
            options={'permissions': [('can_publish_post', 'Can publish post'), ('can_remove_post', 'Can remove post')]},
        ),
    ]
