# Generated by Django 4.2.5 on 2023-11-26 02:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_lat_item_location_name_item_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
