# Generated by Django 4.2.5 on 2023-09-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_item_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/item_thumbnails/'),
        ),
    ]
