# Generated by Django 4.2.5 on 2023-09-12 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0007_lendrequest_requestitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendrequest',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lend_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
