# Generated by Django 4.2.5 on 2023-09-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/item_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_med',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/item_images_med/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/item_thumbnails/'),
        ),
    ]
