# Generated by Django 4.2.5 on 2023-09-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_profile_text_userprofile_social_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
