# Generated by Django 4.2.5 on 2023-09-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_item_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_med',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/item_images_med/'),
        ),
    ]
